//! The Rust side of the shared privacy corpus
//! (`fixtures/frontmatter-privacy.json`). The TS classifier
//! (`packages/core/src/markdown/frontmatter-privacy.test.ts`) asserts the
//! same cases, so the two implementations can't drift apart.

use std::fs;
use std::path::{Path, PathBuf};

use reflect_frontmatter::{backup_privacy, BackupPrivacy};
use serde_json::Value;

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
}

fn load(path: PathBuf) -> Value {
    serde_json::from_str(&fs::read_to_string(&path).unwrap())
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()))
}

fn corpus_cases() -> Vec<Value> {
    let corpus = load(fixtures().join("frontmatter-privacy.json"));
    let cases = corpus["cases"].as_array().unwrap().clone();
    assert!(cases.len() > 50, "the corpus lost its cases");
    cases
}

/// A verdict as the corpus spells it: class, plus the reason when unreadable.
fn spelled(privacy: BackupPrivacy) -> (&'static str, Option<&'static str>) {
    match privacy {
        BackupPrivacy::Public => ("public", None),
        BackupPrivacy::Private => ("private", None),
        BackupPrivacy::Unreadable(reason) => ("unreadable", Some(reason.as_str())),
    }
}

/// One side's expectation for a case: its override when the case has one.
fn expectation<'case>(case: &'case Value, side: &str) -> (&'case str, Option<&'case str>) {
    let expected = case.get(side).unwrap_or(case);
    (
        expected["privacy"].as_str().unwrap(),
        expected.get("reason").and_then(Value::as_str),
    )
}

#[test]
fn every_corpus_case_classifies_as_specified() {
    let failures: Vec<String> = corpus_cases()
        .iter()
        .filter_map(|case| {
            let source = case["source"].as_str().unwrap();
            let got = spelled(backup_privacy(source.as_bytes()));
            let want = expectation(case, "rust");
            (got != want).then(|| format!("{}: got {got:?}, want {want:?}", case["name"]))
        })
        .collect();
    assert!(failures.is_empty(), "\n{}", failures.join("\n"));
}

/// The two parsers may disagree on a case's class, never on whether the note
/// is withheld: every note TS treats as private is private or unreadable
/// here, and vice versa.
#[test]
fn both_sides_agree_on_what_is_withheld() {
    for case in corpus_cases() {
        let withheld = |side| expectation(&case, side).0 != "public";
        assert_eq!(withheld("rust"), withheld("ts"), "{}", case["name"]);
        if case.get("rust").is_some() || case.get("ts").is_some() {
            assert!(
                case["why"].as_str().is_some_and(|why| !why.is_empty()),
                "{}: an override needs a `why`",
                case["name"]
            );
        }
    }
}

/// The TS↔Rust parity corpus (`fixtures/parity`): `expected.json`'s `private`
/// is the TS index bit, generated by the core pipeline. Every note it marks
/// private is withheld here, and every note withheld here is marked private.
#[test]
fn the_parity_corpus_agrees_with_the_ts_index_bit() {
    let parity = fixtures().join("parity");
    let expected = load(parity.join("expected.json"));
    let notes = expected["notes"].as_object().unwrap();
    assert!(notes
        .values()
        .any(|note| note["private"].as_bool() == Some(true)));
    for (rel_path, want) in notes {
        let bytes = fs::read(parity.join(rel_path)).unwrap();
        assert_eq!(
            !backup_privacy(&bytes).is_public(),
            want["private"].as_bool().unwrap(),
            "{rel_path}"
        );
    }
}
