export {
  gitStatus,
  gitNoteVersion,
  gitSetup,
  gitCommitAll,
  gitFetch,
  gitMergeRemote,
  gitPush,
  isDeviceFlowConfigured,
  githubAppInstallUrl,
  saveGithubAuth,
  loadGithubAuth,
  clearGithubAuth,
  deviceFlowStart,
  deviceFlowPoll,
  runDeviceFlow,
  getGithubToken,
  gitDisconnect,
  gitClone,
  parseGithubRemote,
  githubRemoteUrl,
  newRepoUrl,
  createGithubRepo,
  getGithubRepo,
  getAuthenticatedUser,
  createGist,
  updateGist,
  deleteGist,
  createSyncEngine,
  isSyncError,
  type GitStatus,
  type CommitOutcome,
  type MergeOutcome,
  type PushOutcome,
  type SkippedFile,
  type ChangedFile,
  type DisplacedFile,
  type GithubAuth,
  type DeviceFlowStart,
  type DevicePollResult,
  type GithubRepoRef,
  type GithubRepo,
  type GithubUser,
  type PublishedGist,
  type GistFile,
  type SyncEngine,
  type SyncEngineOptions,
  type SyncErrorKind,
  type SyncStatus,
} from '../sync/index.ts'
export {
  frontmatterSchema,
  gistFrontmatterSchema,
  gistBodyHash,
  gistFilename,
  isPinned,
  pinnedOrder,
  PARSED_NOTE_VERSION,
  parseNote,
  countDisplayChars,
  appendBlock,
  wikiLinkSafe,
  retitleWikiLinks,
  type WikiLinkRetitleOptions,
  setTaskDueDate,
  clearTaskDueDate,
  TaskStaleError,
  renderInlineText,
  compareTaskPaths,
  decodeTaskPath,
  encodeTaskPath,
  isSameTaskPath,
  applyTaskEdits,
  findTaskMove,
  getTaskDueDate,
  projectTasks,
  NoteNotSerializableError,
  type InsertPosition,
  type ParsedTask,
  type TaskEdit,
  type TaskEditInsert,
  type TaskEditItem,
  type TaskEditResult,
  type TaskMove,
  type TaskLocator,
  type TaskSnapshot,
  resolved,
  resolveWikiLink,
  resolveWikiLinkAsync,
  unresolved,
  splitFrontmatter,
  parseFrontmatter,
  frontmatterPrivacy,
  upsertFrontmatter,
  detectConflictMarkers,
  parseConflictMarkers,
  resolveConflictMarkers,
  conflictMarkerBlockCount,
  conflictMarkerLabels,
  type ConflictMarkerLabels,
  type ConflictSegment,
  type ConflictSide,
  parseBody,
  displayNoteTitle,
  wikiLinkTargetForTitle,
  scanInlineWikiLinks,
  scanInlineImages,
  scanInlineSegments,
  foldFallbackTitleKey,
  foldKey,
  foldTag,
  isTagName,
  hasAuthoredTitle,
  normalizeWikiTarget,
  slugForTitle,
  type ConflictResolution,
  type Frontmatter,
  type GistFrontmatter,
  type Span,
  type WikiLink,
  type MarkdownLink,
  type Heading,
  type AssetRef,
  type ParsedNote,
  type InlineWikiLink,
  type InlineImage,
  type InlineSegment,
  type FrontmatterSplit,
  type ParsedFrontmatter,
  type FrontmatterPrivacy,
  type UnreadableFrontmatterReason,
  type NormalizedTarget,
  type Resolution,
  type WikiLookup,
  type AsyncWikiLookup,
} from '../markdown/index.ts'
export {
  openIndex,
  applyIndexedNote,
  applyIndexedNotes,
  removeFromIndex,
  moveNoteIndexed,
  clearIndex,
  watchStart,
  watchStop,
  subscribeIndexChanges,
  subscribeIndexApplied,
  type IndexAppliedListener,
  subscribeIndexWritten,
  subscribeNoteMoved,
  subscribeNoteDisplaced,
  recordDisplacedNotes,
  setDisplacedNotesGeneration,
  isRecentlyDisplaced,
  clearDisplacedNotes,
  type NoteDisplacement,
  subscribeFileChanges,
  subscribeReconcileRequests,
  emitFileChanges,
  setLocalWriteEcho,
  subscribeOwnWrites,
  subscribeIcloudConflicts,
  subscribeIcloudWatchFailed,
  applyIndexChanges,
  hashContent,
  cjkColumnText,
  buildIndexedNote,
  CLAIM_TIER,
  decodeTaskBreadcrumbs,
  encodeTaskBreadcrumbs,
  indexedNoteSchema,
  indexedLinkSchema,
  indexedAliasSchema,
  indexNote,
  reindexNotesReferencing,
  rebuildIndex,
  reconcileIndex,
  syncIndex,
  getIndexMeta,
  setIndexMeta,
  dailyDatesInRange,
  listDailyActivity,
  listDailyEditCounts,
  activityLevel,
  activityThresholds,
  heatmapWeeks,
  monthLabelColumns,
  getBacklinks,
  getBacklinksWithContext,
  getConflictedNotes,
  getDuplicateNoteIds,
  getLinkSources,
  getPathLinkSources,
  getNote,
  getNoteMtime,
  getNotesByTag,
  getOpenTasks,
  getCompletedTasks,
  groupTaskContexts,
  groupTasks,
  taskDateBucket,
  tasksForDay,
  listDailyNotes,
  buildAttachmentLibrary,
  listAttachmentNoteTags,
  listAttachmentReferences,
  listAttachmentPreviews,
  listNotes,
  sortNoteListRows,
  chooseNoteListSort,
  reverseNoteListSort,
  listOnThisDay,
  listNoteTags,
  listRecentNotes,
  getPinnedNotes,
  searchNotes,
  aliasHint,
  suggestWikiTargets,
  suggestWikiLinkTargets,
  suggestTags,
  generateDateSuggestions,
  serializeWikiSuggestionAddress,
  getIndexedFileFacts,
  getIndexedFileFactsByPath,
  resolveWikiTarget,
  resolveNoteTarget,
  rewriteLinksForTitleChange,
  rewritePathLinksForMove,
  nextAliases,
  availableTemplatePath,
  slugPathForTitle,
  templateSlugPathForTitle,
  listTemplates,
  type TemplateEntry,
  cleanSnippetText,
  parseHighlights,
  randomNotePath,
  parseSearchQuery,
  searchWithFilters,
  type IndexedNote,
  type IndexedLink,
  type IndexedAlias,
  type Backlink,
  type BacklinkContext,
  type BacklinkContextPage,
  type BacklinkContextPageOptions,
  type BacklinkSourceCursor,
  type SnippetTask,
  type ConflictedNote,
  type DailyNoteRow,
  type DailyNotesRange,
  type DailyActivity,
  type DailyEditCount,
  type ActivityLevel,
  type ActivityThresholds,
  type OnThisDayEntry,
  type DayTasks,
  type DuplicateIdGroup,
  type NoteRow,
  type OpenTask,
  type TaskContext,
  type TaskGroup,
  type TaskGroupKind,
  type NoteListEntry,
  type NoteListOptions,
  type PreviewableAttachmentType,
  type AttachmentLibraryEntry,
  type AttachmentNoteRef,
  type AttachmentNoteTagRow,
  type AttachmentReferenceRow,
  type NoteListSort,
  type NoteListSortKey,
  type SortDirection,
  type NoteTagFacet,
  type RecentNoteRow,
  type RecentNotesOptions,
  type PinnedNote,
  type SearchHit,
  type TagSuggestion,
  type WikiLinkSuggestionResult,
  type FileChange,
  type WikiSuggestion,
  type WikiLinkSuggestion,
  type GeneratedDate,
  type DateSuggestionContext,
  type HighlightSegment,
  type ParsedSearchQuery,
  type SearchFilters,
  type FilteredSearchHit,
  type FilteredSearchOptions,
  type RenameBacklink,
  type RenameIo,
  type TitleRenameRewriteOptions,
  type TitleRenameRewriteResult,
} from '../indexing/index.ts'
